/**
 * @file LLM-powered conversation engine for the DM Responder agent.
 */

import axios from 'axios';
import dotenv from 'dotenv';
import { SYSTEM_PROMPT } from './prompts.js';
import { validateConversation } from './utils.js';

// Load environment variables from .env file
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

/**
 * Generates a response for a conversation using an LLM.
 *
 * @param {Object} params
 * @param {Array} params.conversationHistory - Array of {role, text} objects
 * @returns {Promise<Object>} Response object with next_message, stage, reasoning, etc.
 */
export async function generateResponse({ conversationHistory, leadContext = null, profileConfig = null }) {
  // Validate input
  validateConversation(conversationHistory);

  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set in the environment variables.');
  }

  try {
    // The user's last message is the prompt for the LLM
    const llmResponse = await getLlmResponse(conversationHistory, leadContext, profileConfig);

    // Structure the response to match the expected output format
    return {
      next_message: llmResponse.message,
      conversation_stage: "llm_generation",
      message_type: "empathy_and_discovery",
      reasoning: "Generated by LLM.",
      step_used: llmResponse.step_used || null, // Pass the detected step back
      alternative_approaches: [
        "Ask a more direct question about their challenges.",
        "Share a relatable, brief anecdote.",
        "Offer a small piece of actionable advice to build trust."
      ],
      next_steps: [
        "Wait for their response.",
        "Analyze the response for pain points and goals.",
        "Continue building trust before suggesting any next steps."
      ]
    };
  } catch (error) {
    console.error("Error generating LLM response:", error.response ? error.response.data : error.message);
    throw new Error('Failed to get a response from the LLM.');
  }
}

/**
 * Generates a specific revival message when the last interaction was not a question.
 */
export async function generateRevivalMessage(conversationHistory, leadContext) {
  if (!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY required');

  const systemPrompt = `
    You are an Instagram outreach expert. 
    Your goal is to re-engage a prospect who has stopped replying.
    
    CONTEXT:
    The last message you sent was NOT a question (e.g., "Ok no problem", "Understood").
    You must now send a friendly follow-up question to restart the conversation.
    
    INSTRUCTIONS:
    1. Analyze the conversation history, especially the prospect's last message (excuse, objection, busy, etc.).
    2. Generate a SHORT, casual, and empathetic question.
    3. Example: If they said "I'm busy", ask "Hey, how are you? Did you find some time for yourself?"
    4. Example: If they said "I'll watch later", ask "Coucou! Did you get a chance to watch the video?"
    5. Be subtle. Do not sound desperate.
    6. Language: MATCH THE LANGUAGE OF THE CONVERSATION (French or English).
  `;

  return getLlmResponse(conversationHistory, leadContext, { 
      dm_responder: { system_prompt: systemPrompt } 
  });
}

/**
 * Calls the OpenAI API to get a contextual response.
 * @param {Array} conversationHistory - The history of the conversation.
 * @returns {Promise<string>} The text of the next message.
 */
async function getLlmResponse(conversationHistory, leadContext, profileConfig = null) {
  const headers = {
    'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
    'Content-Type': 'application/json',
  };

  // Build a context description if available
  let contextDescription = "";
  if (leadContext) {
    contextDescription = `\n\nCONTEXTE DU PROSPECT (Utilise ces infos pour personnaliser l'échange) :\n`;
    if (leadContext.username) contextDescription += `- Username: @${leadContext.username}\n`;
    if (leadContext.fullName) contextDescription += `- Nom: ${leadContext.fullName}\n`;
    if (leadContext.biography) contextDescription += `- Bio: ${leadContext.biography}\n`;
    if (leadContext.pain_points) contextDescription += `- Problèmes identifiés: ${leadContext.pain_points}\n`;
    if (leadContext.goals) contextDescription += `- Objectifs: ${leadContext.goals}\n`;
    if (leadContext.conversation_step) contextDescription += `- Étape actuelle (1-6): ${leadContext.conversation_step}\n`;
    if (leadContext.notes) contextDescription += `- Notes: ${leadContext.notes}\n`;
  }

  // Determine System Prompt
  let systemPrompt = SYSTEM_PROMPT;
  if (profileConfig && profileConfig.dm_responder && profileConfig.dm_responder.system_prompt) {
      systemPrompt = profileConfig.dm_responder.system_prompt;
  }

  // Force JSON output instruction
  systemPrompt += `
  
  IMPORTANT: Ton output DOIT être un JSON valide, sans markdown, au format suivant :
  {
      "message": "Le texte du message à envoyer",
      "step_used": 3 
  }
  "step_used" correspond au numéro de l'étape du script que tu viens d'utiliser (1, 2, 3, 4 ou 5). Si tu es hors script, mets null.
  `;

  // The messages payload starts with the system prompt + context
  const messages = [
    { role: 'system', content: systemPrompt + contextDescription },
    ...conversationHistory.map(msg => ({ role: msg.role, content: msg.text })),
  ];

  const data = {
    model: 'gpt-4o', // Or 'gpt-3.5-turbo' for faster, cheaper responses
    messages: messages,
    temperature: 0.7, // A bit of creativity
    max_tokens: 1024,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
    response_format: { type: "json_object" } // Enforce JSON mode
  };

  const response = await axios.post(OPENAI_API_URL, data, { headers });

  if (response.data.choices && response.data.choices.length > 0) {
    const rawContent = response.data.choices[0].message.content.trim();
    try {
        const json = JSON.parse(rawContent);
        return { message: json.message, step_used: json.step_used };
    } catch (e) {
        // Fallback if model fails JSON (rare with JSON mode)
        console.warn("LLM didn't output valid JSON, falling back to raw text.");
        return { message: rawContent, step_used: null };
    }
  } else {
    throw new Error('No response choices returned from the API.');
  }
}
