/**
 * @file LLM-powered conversation engine for the DM Responder agent.
 */

import axios from 'axios';
import dotenv from 'dotenv';
import { SYSTEM_PROMPT } from './prompts.js';
import { validateConversation } from './utils.js';
import { composeSystemPrompt } from '../../../shared/domain/services/PromptComposer.js';

// Load environment variables from .env file
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

// Cache for prompt data to avoid repeated DB queries
const promptCache = new Map();

/**
 * Generates a response for a conversation using an LLM.
 *
 * @param {Object} params
 * @param {Array} params.conversationHistory - Array of {role, text} objects
 * @returns {Promise<Object>} Response object with next_message, stage, reasoning, etc.
 */
export async function generateResponse({ conversationHistory, leadContext = null, profileConfig = null }) {
  // Validate input
  validateConversation(conversationHistory);

  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set in the environment variables.');
  }

  try {
    // The user's last message is the prompt for the LLM
    const llmResponse = await getLlmResponse(conversationHistory, leadContext, profileConfig);

    // Structure the response to match the expected output format
    return {
      next_message: llmResponse.message,
      message_type: "empathy_and_discovery",
      reasoning: "Generated by LLM.",
      step_used: llmResponse.step_used || null,
      booking_intent: llmResponse.booking_intent || null,
      alternative_approaches: [
        "Ask a more direct question about their challenges.",
        "Share a relatable, brief anecdote.",
        "Offer a small piece of actionable advice to build trust."
      ],
      next_steps: [
        "Wait for their response.",
        "Analyze the response for pain points and goals.",
        "Continue building trust before suggesting any next steps."
      ]
    };
  } catch (error) {
    console.error("Error generating LLM response:", error.response ? error.response.data : error.message);
    throw new Error('Failed to get a response from the LLM.');
  }
}

/**
 * Generates a specific revival message when the last interaction was not a question.
 */
export async function generateRevivalMessage(conversationHistory, leadContext) {
  if (!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY required');

  const systemPrompt = `
    You are an Instagram outreach expert. 
    Your goal is to re-engage a prospect who has stopped replying.
    
    CONTEXT:
    The last message you sent was NOT a question (e.g., "Ok no problem", "Understood").
    You must now send a friendly follow-up question to restart the conversation.
    
    INSTRUCTIONS:
    1. Analyze the conversation history, especially the prospect's last message (excuse, objection, busy, etc.).
    2. Generate a SHORT, casual, and empathetic question.
    3. Example: If they said "I'm busy", ask "Hey, how are you? Did you find some time for yourself?"
    4. Example: If they said "I'll watch later", ask "Coucou! Did you get a chance to watch the video?"
    5. Be subtle. Do not sound desperate.
    6. Language: MATCH THE LANGUAGE OF THE CONVERSATION (French or English).
  `;

  return getLlmResponse(conversationHistory, leadContext, { 
      dm_responder: { system_prompt: systemPrompt } 
  });
}

/**
 * Get the system prompt from database for an account
 * @param {number} accountId - The account ID
 * @returns {Promise<string|null>} The composed system prompt or null if not configured
 */
async function getPromptFromDatabase(accountId) {
  if (!accountId) return null;

  // Check cache first
  const cacheKey = `prompt_${accountId}`;
  if (promptCache.has(cacheKey)) {
    const cached = promptCache.get(cacheKey);
    // Cache for 5 minutes
    if (Date.now() - cached.timestamp < 5 * 60 * 1000) {
      return cached.prompt;
    }
  }

  try {
    const { getContainer } = await import('../../../shared/container.js');
    const container = await getContainer();
    const funnelRepo = container.repositories.funnel;

    const { persona, stages } = await funnelRepo.getPromptData(accountId);

    // Check if we have conversation scripts in the database
    const hasScripts = stages.some(s => s.conversationScript);

    if (!hasScripts && !persona) {
      // No database config, will fall back to config file
      return null;
    }

    const prompt = composeSystemPrompt({ persona, stages });

    // Cache the result
    promptCache.set(cacheKey, { prompt, timestamp: Date.now() });

    return prompt;
  } catch (error) {
    console.error('[Engine] Failed to get prompt from database:', error.message);
    return null;
  }
}

/**
 * Clear the prompt cache (useful after updates)
 */
export function clearPromptCache(accountId = null) {
  if (accountId) {
    promptCache.delete(`prompt_${accountId}`);
  } else {
    promptCache.clear();
  }
}

/**
 * Calls the OpenAI API to get a contextual response.
 * @param {Array} conversationHistory - The history of the conversation.
 * @returns {Promise<string>} The text of the next message.
 */
async function getLlmResponse(conversationHistory, leadContext, profileConfig = null) {
  const headers = {
    'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
    'Content-Type': 'application/json',
  };

  // Build a context description if available
  let contextDescription = "";
  if (leadContext) {
    contextDescription = `\n\nCONTEXTE DU PROSPECT (Utilise ces infos pour personnaliser l'échange) :\n`;
    if (leadContext.username) contextDescription += `- Username: @${leadContext.username}\n`;
    if (leadContext.fullName) contextDescription += `- Nom: ${leadContext.fullName}\n`;
    if (leadContext.biography) contextDescription += `- Bio: ${leadContext.biography}\n`;
    if (leadContext.pain_points) contextDescription += `- Problèmes identifiés: ${leadContext.pain_points}\n`;
    if (leadContext.goals) contextDescription += `- Objectifs: ${leadContext.goals}\n`;
    if (leadContext.funnel_step) contextDescription += `- Étape actuelle du funnel (1-9): ${leadContext.funnel_step}\n`;
    if (leadContext.notes) contextDescription += `- Notes: ${leadContext.notes}\n`;
  }

  // Determine System Prompt (priority: database > profileConfig > default)
  let systemPrompt = SYSTEM_PROMPT;

  // Try to get prompt from database first (if accountId is available)
  const accountId = leadContext?.account_id || profileConfig?.account_id || null;
  if (accountId) {
    const dbPrompt = await getPromptFromDatabase(accountId);
    if (dbPrompt) {
      systemPrompt = dbPrompt;
    }
  }

  // Fall back to config file if no database prompt
  if (systemPrompt === SYSTEM_PROMPT && profileConfig?.dm_responder?.system_prompt) {
    systemPrompt = profileConfig.dm_responder.system_prompt;
  }

  // === RAG ENRICHMENT ===
  // Retrieve relevant knowledge and similar conversations (accountId already defined above)
  if (accountId) {
    try {
      const { getContainer } = await import('../../../shared/container.js');
      const container = await getContainer();
      const ragRetriever = container.services.ragRetriever;

      // Get the last prospect message
      const lastProspectMessage = conversationHistory
        .filter(m => m.role === 'user')
        .pop()?.text || '';

      if (lastProspectMessage) {
        const ragResults = await ragRetriever.retrieve({
          prospectMessage: lastProspectMessage,
          leadContext,
          accountId
        });

        if (ragRetriever.hasRelevantResults(ragResults)) {
          const ragContext = ragRetriever.formatForPrompt(ragResults);
          contextDescription += `\n\n${ragContext}`;
          console.log(`[Engine] RAG enriched context with ${ragResults.relevantKnowledge.length} knowledge entries`);
        }
      }
    } catch (e) {
      console.error('[Engine] RAG retrieval failed (continuing without):', e.message);
      // Continue without RAG - graceful degradation
    }
  }

  // Inject Calendly Availability if in booking stage (Step 5+)
  const currentStep = leadContext?.funnel_step || 0;
  if (currentStep >= 5) {
      try {
          const { fetchAvailability } = await import('../../../shared/utils/calendly.js');
          // Get profile name from DB account or config fallback
          let profileName = profileConfig?.profile_name || 'default';
          if (profileName === 'default' && accountId) {
              try {
                  const { getDb } = await import('../../../agents/collector/src/db/core.js');
                  const db = getDb();
                  if (db) {
                      const acc = db.prepare('SELECT name FROM accounts WHERE id = ?').get(accountId);
                      if (acc) profileName = acc.name;
                  }
              } catch (e) {}
          }
          const availability = await fetchAvailability(profileName);

          const formatSlot = (s) => {
              const d = new Date(s.start_time);
              return d.toLocaleString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit', timeZone: 'Europe/Paris' });
          };

          const hasThisWeek = availability.thisWeek?.primary?.length > 0;
          const hasNextWeek = availability.nextWeek?.primary?.length > 0;

          if (hasThisWeek || hasNextWeek) {
              contextDescription += `\n\nDISPONIBILITÉS CALENDLY RÉELLES :\n`;

              if (hasThisWeek) {
                  contextDescription += `\nCETTE SEMAINE :\n`;
                  contextDescription += `- PROPOSITION PRIMAIRE : ${availability.thisWeek.primary.map(formatSlot).join(', ')}\n`;
                  if (availability.thisWeek.backup.length > 0) {
                      contextDescription += `- PROPOSITION DE SECOURS : ${availability.thisWeek.backup.map(formatSlot).join(', ')}\n`;
                  }
              }

              if (hasNextWeek) {
                  contextDescription += `\nSEMAINE PROCHAINE :\n`;
                  contextDescription += `- PROPOSITION PRIMAIRE : ${availability.nextWeek.primary.map(formatSlot).join(', ')}\n`;
                  if (availability.nextWeek.backup.length > 0) {
                      contextDescription += `- PROPOSITION DE SECOURS : ${availability.nextWeek.backup.map(formatSlot).join(', ')}\n`;
                  }
              }

              contextDescription += `\nINSTRUCTIONS :\n`;
              contextDescription += `- ⚠️ TOUS les créneaux ci-dessus sont en HEURE DE PARIS (Europe/Paris). Ne tente JAMAIS de convertir toi-même vers un autre fuseau horaire. Si le prospect mentionne être dans un autre pays/fuseau, précise simplement "(heure de Paris)" à côté des créneaux proposés.\n`;
              contextDescription += `- Propose d'abord les créneaux CETTE SEMAINE.\n`;
              contextDescription += `- Si le prospect dit ne pas pouvoir cette semaine ou demande la semaine prochaine → propose les créneaux SEMAINE PROCHAINE.\n`;
              contextDescription += `- Si le lead a validé un créneau mais n'a pas donné son EMAIL/TÉLÉPHONE -> [STEP_7]. Demande ses coordonnées.\n`;
              contextDescription += `- Si le lead a donné ses coordonnées -> [STEP_8]. Confirmation chaleureuse.\n`;
          } else {
              contextDescription += `\n\n⚠️ AUCUN CRÉNEAU CALENDLY DISPONIBLE. N'invente PAS de créneaux. Demande simplement au prospect quand il serait disponible dans la semaine et dis-lui que tu reviendras vers lui avec des créneaux précis.\n`;
          }
      } catch (e) {
          console.error("[Engine] Failed to fetch Calendly availability:", e.message);
          contextDescription += `\n\n⚠️ AUCUN CRÉNEAU CALENDLY DISPONIBLE. N'invente PAS de créneaux. Demande simplement au prospect quand il serait disponible dans la semaine et dis-lui que tu reviendras vers lui avec des créneaux précis.\n`;
      }
  }

  // Force JSON output instruction
  systemPrompt += `
  
  IMPORTANT: Ton output DOIT être un JSON valide, sans markdown, au format suivant :
  {
      "message": "Le texte du message à envoyer",
      "step_used": "6",
      "booking_intent": {
          "slot": "2026-02-05T14:00:00Z",
          "email": "lead@mail.com",
          "phone": "06..."
      }
  }
  "step_used" correspond au numéro de l'étape du script que tu viens d'utiliser (1, 2, 3, 4, 5, 6, 7, 8 ou 9).
  "booking_intent" ne doit être rempli QUE si tu as TOUTES les informations (créneau choisi, email, téléphone) pour valider le RDV. Sinon, mets null.
  `;


  // The messages payload starts with the system prompt + context
  const messages = [
    { role: 'system', content: systemPrompt + contextDescription },
    ...conversationHistory.map(msg => ({ role: msg.role, content: msg.text })),
  ];

  const data = {
    model: 'gpt-4o', // Or 'gpt-3.5-turbo' for faster, cheaper responses
    messages: messages,
    temperature: 0.7, // A bit of creativity
    max_tokens: 1024,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
    response_format: { type: "json_object" } // Enforce JSON mode
  };

  const response = await axios.post(OPENAI_API_URL, data, { headers });

  if (response.data.choices && response.data.choices.length > 0) {
    const rawContent = response.data.choices[0].message.content.trim();
    try {
        const json = JSON.parse(rawContent);
        return { message: json.message, step_used: json.step_used, booking_intent: json.booking_intent || null };
    } catch (e) {
        // Fallback if model fails JSON (rare with JSON mode)
        console.warn("LLM didn't output valid JSON, falling back to raw text.");
        return { message: rawContent, step_used: null };
    }
  } else {
    throw new Error('No response choices returned from the API.');
  }
}
