/**
 * @file LLM-powered conversation engine for the DM Responder agent.
 */

import axios from 'axios';
import dotenv from 'dotenv';
import { SYSTEM_PROMPT } from './prompts.js';
import { validateConversation } from './utils.js';

// Load environment variables from .env file
dotenv.config();

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

/**
 * Generates a response for a conversation using an LLM.
 *
 * @param {Object} params
 * @param {Array} params.conversationHistory - Array of {role, text} objects
 * @returns {Promise<Object>} Response object with next_message, stage, reasoning, etc.
 */
export async function generateResponse({ conversationHistory, leadContext = null, profileConfig = null }) {
  // Validate input
  validateConversation(conversationHistory);

  if (!OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set in the environment variables.');
  }

  try {
    // The user's last message is the prompt for the LLM
    const llmResponseText = await getLlmResponse(conversationHistory, leadContext, profileConfig);

    // Structure the response to match the expected output format
    return {
      next_message: llmResponseText,
      conversation_stage: "llm_generation", // Stage is now dynamic based on LLM
      message_type: "empathy_and_discovery", // Type is also dynamic
      reasoning: "The response was generated by the LLM based on the conversation history and the system prompt, focusing on empathetic discovery.",
      alternative_approaches: [
        "Ask a more direct question about their challenges.",
        "Share a relatable, brief anecdote.",
        "Offer a small piece of actionable advice to build trust."
      ],
      next_steps: [
        "Wait for their response.",
        "Analyze the response for pain points and goals.",
        "Continue building trust before suggesting any next steps."
      ]
    };
  } catch (error) {
    console.error("Error generating LLM response:", error.response ? error.response.data : error.message);
    throw new Error('Failed to get a response from the LLM.');
  }
}

/**
 * Calls the OpenAI API to get a contextual response.
 * @param {Array} conversationHistory - The history of the conversation.
 * @returns {Promise<string>} The text of the next message.
 */
async function getLlmResponse(conversationHistory, leadContext, profileConfig = null) {
  const headers = {
    'Authorization': `Bearer ${OPENAI_API_KEY}`,
    'Content-Type': 'application/json',
  };

  // Build a context description if available
  let contextDescription = "";
  if (leadContext) {
    contextDescription = `\n\nCONTEXTE DU PROSPECT (Utilise ces infos pour personnaliser l'échange) :\n`;
    if (leadContext.username) contextDescription += `- Username: @${leadContext.username}\n`;
    if (leadContext.fullName) contextDescription += `- Nom: ${leadContext.fullName}\n`;
    if (leadContext.biography) contextDescription += `- Bio: ${leadContext.biography}\n`;
    if (leadContext.pain_points) contextDescription += `- Problèmes identifiés: ${leadContext.pain_points}\n`;
    if (leadContext.goals) contextDescription += `- Objectifs: ${leadContext.goals}\n`;
    if (leadContext.notes) contextDescription += `- Notes: ${leadContext.notes}\n`;
  }

  // Determine System Prompt
  let systemPrompt = SYSTEM_PROMPT;
  if (profileConfig && profileConfig.dm_responder && profileConfig.dm_responder.system_prompt) {
      systemPrompt = profileConfig.dm_responder.system_prompt;
  }

  // The messages payload starts with the system prompt + context
  const messages = [
    { role: 'system', content: systemPrompt + contextDescription },
    ...conversationHistory.map(msg => ({ role: msg.role, content: msg.text })),
  ];

  const data = {
    model: 'gpt-4o', // Or 'gpt-3.5-turbo' for faster, cheaper responses
    messages: messages,
    temperature: 0.7, // A bit of creativity
    max_tokens: 500,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
  };

  const response = await axios.post(OPENAI_API_URL, data, { headers });

  if (response.data.choices && response.data.choices.length > 0) {
    return response.data.choices[0].message.content.trim();
  } else {
    throw new Error('No response choices returned from the API.');
  }
}
